import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const ZONE = 'domains';
const STATE = 'domains/.state.json';

const state = { _comment: 'Auto-generated by deploy.yml. Do not edit by hand.' };

let entries;
try { entries = readdirSync(ZONE); } catch { entries = []; }

let existing = {};
try { existing = JSON.parse(readFileSync(STATE, 'utf8')); } catch { /* no existing state */ }

for (const e of entries) {
  if (!e.endsWith('.json') || e.startsWith('.')) continue;
  const name = e.replace(/\.json$/, '');
  if (existing[name]) state[name] = existing[name];
}

writeFileSync(STATE, JSON.stringify(state, null, 2) + '\n');
console.log(`Updated ${STATE} with ${Object.keys(state).length - 1} entries.`);
